### ISSUE TITLE
Plugin promos not displayed correctly

### ISSUE THREAD

**Issue by andykeith** [barn2plugins/woocommerce-product-tabs#11]
Tested with WTA 2.1.2. 

The plugin promos under Products > Product Tabs > Settings aren't displayed correctly. See screenshot below.

<img width="1855" alt="Screenshot 2024-02-06 at 15 27 19" src="https://github.com/barn2plugins/woocommerce-product-tabs/assets/4103194/dbdf4542-a711-4d3a-8a22-e05d0496c5f1">

**Comment by amirition** [comment]
This has been fixed in version 2.1.3.
