### ISSUE TITLE
Add use statement for WP_Embed

### ISSUE THREAD

**Issue by andykeith** [barn2plugins/woocommerce-product-tabs#12]
Please can you add a `use` statement for `WP_Embed` to this class: `Barn2\Plugin\WC_Product_Tabs_Free\Product_Tabs`

This will fix [the issue](https://wordpress.org/support/topic/fatal-error-in-version-2-1-2) reported on the support forum by anjanphukan. 

The use statement will be:

```
use Barn2\Plugin\WC_Product_Tabs_Free\Dependencies\Lib\Registerable;
use Barn2\Plugin\WC_Product_Tabs_Free\Dependencies\Lib\Service;
use WP_Embed;
```

Also, can you add parentheses when the `WP_Embed` class is created on line 167. This will fix the phpcs warning.

`$embed = new WP_Embed();`

**Comment by amirition** [comment]
This has been fixed in version 2.1.3.
