### ISSUE TITLE
Enable compatibility mode for page builders option doesn't work

### ISSUE THREAD

**Issue by andykeith** [barn2plugins/woocommerce-product-tabs#13]
Ticking or unticking the "Enable compatibility mode for page builders" option doesn't do anything. Checking the code, it looks like there's an error on this line:

```
$disable_the_content_filter = get_option( 'wpt_disable_content_filter' );
```

This option no longer exists in the settings as it appears all options are stored in an array under the key `wpt_options`. 

Can you check if the Pro version has the same issue as well?

**Comment by amirition** [comment]
This has been fixed in version 2.1.3.
