### ISSUE TITLE
'Screen Options' & 'Help' tabs in the Edit product page are hidden

### ISSUE THREAD

**Issue by FaycalBoutam** [barn2plugins/woocommerce-product-tabs#14]
@ejpadero report:

> ======Full Description======
> If/When WTA Free is active, if you go to the Edit product page of any product, the Screen Options tand Help tabs do not appear/display/show for some reason.
> 
> Screenshots:
> WTA (Free) active: https://share.zight.com/lluWmX7W
> WTA (Free) deactivated: https://share.zight.com/6quo9JJz
> 
> This behavior is replicated on a test site.
> 
> ======Expected Outcome======
> The Screen Options and Help tabs appear/display/show in the Edit product page when WTA (Free) is active.
> 
> ======Observed/Actual Outcome======
> The Screen Options and Help tabs do not appear/display/show in the Edit product page when WTA (Free) is active.
> 
> ======Steps to Replicate ======
> Activate WTA (Free) on a site.
> Go to the Edit product page of any product.

Caused by this [line](https://github.com/barn2plugins/woocommerce-product-tabs/blob/master/assets/css/admin/tab.css#L468).

Ticket: https://secure.helpscout.net/conversation/2573724969/108000?viewId=7603842

**Comment by amirition** [comment]
@FaycalBoutam Thanks for reporting this, I will incldue this in the next update.

**Comment by ejpadero** [comment]
@amirition Acknowledged, with thanks. I've updated the customer with this info.

**Comment by amirition** [comment]
This has been fixed in version 2.1.4.
