### ISSUE TITLE
Issues introduced in 2.1.0

### ISSUE THREAD

**Issue by andykeith** [barn2plugins/woocommerce-product-tabs#6]
While fixing the tab data issue introduced in 2.1.0, I spotted some more problems. Can you look at these as part of the 2.1.1 release:

- The Setup Wizard is broken and displays a white screen. In the log there's an error message which refers to a CSS file which doesn't exist in the repository.
- When upgrading from 2.0.x to 2.1.0, the tab conditions are lost. Any categories selected in 2.0.x are not maintained, and instead the "All products" tick is displayed.

**Comment by amirition** [comment]
@andykeith The issue with the setup wizard is related to the admin styles and is now fixed. I have also fixed the issue with the categories not being shown on the single edit tab. These fixes will be included in the next update.

**Comment by andykeith** [comment]
Perfect, thanks @amirition
