### ISSUE TITLE
When no categories are selected, the Visibility radio button should reset to Global

### ISSUE THREAD

**Issue by andykeith** [barn2plugins/woocommerce-product-tabs#7]
To reproduce:

1. Go to the edit tab page (Products > Product Tabs > Edit)
2. Set the Visibility to "Show on specific categories" 
3. Don't select any categories and save the tab
4. The "Show on specific categories" option remains selected

This doesn't affect the behaviour of the plugin - the tab is displayed globally on all products. However from a user perspective it would be better if the option reverted to "Display globally on all products" if nothing is selected.

This may also affect the Pro plugin.

**Comment by amirition** [comment]
This has been changed in version 2.1.2.
